### ISSUE TITLE
conda dependency missing

### ISSUE THREAD

**Issue by bernt-matthias** [aCLImatise/BiocondaAutomation#4]

**Comment by multimeric** [comment]
Refer to the [conda documentation](https://docs.conda.io/projects/conda/en/latest/api/):

> As of conda 4.5, we do not support pip install conda. However, we are considering that as a supported bootstrap method in the future.

**Comment by multimeric** [comment]
So basically this has to be installed into a conda environment, so it's pointless to add `conda` as a regular python dependency.
