### ISSUE TITLE
use singularity containers for speedup?

### ISSUE THREAD

**Issue by bernt-matthias** [aCLImatise/BiocondaAutomation#5]
since for each conda package there is a singularity container you may simply use the container. should be much faster, since only the container needs to be downloaded. 

In particular because conda's solver is often very slow or even can't resolve at all https://github.com/bioconda/bioconda-recipes/issues/13774

main question is if the containers contain the information on the binaries coming from the package?

**Comment by bernt-matthias** [comment]
Not sure if one can run acclimatise or use argparse2tool (which are obviously not part of the container) from within the container .. but I guess this should be possible as long as they are on a path that is accessible from within the container.

**Comment by multimeric** [comment]
Oh, I didn't know this. Where are the containers located? I can certainly see this speeding things up, but then as you say there's the problem with running stuff inside those containers.

**Comment by bernt-matthias** [comment]
The containers should be here https://biocontainers.pro if I remember correctly. But its docker containers - not singularity.

**Comment by bernt-matthias** [comment]
> but then as you say there's the problem with running stuff inside those containers.

One might use the containers as base image and extend them with the necessary software.

**Comment by multimeric** [comment]
Ah, I know biocontainers. Is there really one for each bioconda package? I thought some were missing.

If it's docker and not singularity that makes it much easier to install things into them.

**Comment by bernt-matthias** [comment]
According to the docs, yes: "Each package added to Bioconda also has a corresponding Docker BioContainer automatically created and uploaded to Quay.io."

I will ask at the bioconda gitter channel
