### ISSUE TITLE
skip post-link.sh and pre-unlink.sh scripts

### ISSUE THREAD

**Issue by bernt-matthias** [aCLImatise/BiocondaAutomation#8]
Seems that the generating process also processes

```
bin/.PACKAGENAMEe-post-link.sh
bin/.PACKAGENAME-pre-unlink.sh
```

**Comment by multimeric** [comment]
Good point. Is there a conda reference to special binaries like this?

**Comment by bernt-matthias** [comment]
I guess here https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html .. 

The text suggests that `pre-link.sh` should be added to the list.
